[libraries]
junit4 = "junit:junit:4.13.2"
mockk = "io.mockk:mockk:1.13.10"
androidx-core-testing = "androidx.arch.core:core-testing:2.2.0"
google-truth = "com.google.truth:truth:1.4.2"
turbine =  "app.cash.turbine:turbine:0.7.0"
coroutine-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.8.0"
emdk-test = "com.symbol:emdk:9.1.1"
androidx-junit-ext = "androidx.test.ext:junit:1.1.5"
androidx-espresso-core = "androidx.test.espresso:espresso-core:3.5.1"
androidx-navigation-testing = "androidx.navigation:navigation-testing:2.7.7"
androidx-fragment-testing = "androidx.fragment:fragment-testing:1.6.2"
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-test-core = "androidx.test:core:1.5.0"

[bundles]

unitTesting = [
    "junit4",
    "mockk",
    "androidx-core-testing",
    "google-truth",
    "turbine",
    "coroutine-test",
    "emdk-test"
]

androidTesting = [
    "androidx-junit-ext",
    "androidx-espresso-core",
    "androidx-test-core"
]